- .github/workflows/flow-pull-request-checks.yaml
- .github/workflows/zxc-build-library.yaml
- CMakePresets.json
Updates the workflows to use the new ARC cluster and fixes remaining deprecation warnings due to `set-output` usage in the steps.
- Closes #5
> Migrate Actions workflows to new cluster

- BuildOpenSSL.cmake
- CMakeLists.txt
- src/proto/CMakeLists.txt
- vcpkg.json
This PR incorporates the same changes as the [Hedera C++ SDK](https://github.com/hashgraph/hedera-sdk-cpp/pull/162). It pulls in `master` OpenSSL and builds and links to gRPC so that versions can be consistent.
Fixes #7 
**Checklist**
> Build OpenSSL from source

- CMakeLists.txt
This PR updates the C++ protobufs to v0.35 of the Hedera protobufs.
Fixes #16 
**Checklist**
> Upgrade to v0.35 of Hedera protobufs

- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR adds missing `*.proto` files to the C++ protobufs for use by the C++ SDK.
**NOTE:** this should be approved after #21 
Fixes #18
> Install all `*.proto` files

- .github/workflows/zxc-build-library.yaml
- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR upgrades the C++ protobufs to `v0.40.0` of the Hedera protobufs. 
**Fixes:** https://github.com/hashgraph/hedera-protobufs-cpp/issues/24
**Checklist**
> Upgrade to `v0.40.0` of Hedera protobufs

- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR fixes an issue caused by including unnecessary `.proto` files in the build. Files were getting overwritten and causing issues adding features to the C++ SDK.
Fixes #26 
**Checklist**
> Remove unnecessary `.proto` files

- .gitignore
- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR adds the mirror node protobufs so that the C++ SDK may communicate with the mirror nodes.
Fixes #28 
**Checklist**
> Add mirror node protobufs

- .github/workflows/zxc-build-library.yaml
- CMakeLists.txt
This PR upgrades the `Hedera C++ protobufs` to use `v0.41.0` of the `Hedera Protobufs API`.
**Fixes:** https://github.com/hashgraph/hedera-protobufs-cpp/issues/30
**Checklist**
> Upgrade to `v0.41.0` of Hedera Protobufs (PR)

- .github/workflows/flow-pull-request-checks.yaml
- .github/workflows/zxc-build-library.yaml
This PR introduces some optimisations for the GitHub Action of `PR Checks`. The following steps will be skipped during the PR process:
- `CMake Build (Release)`
- `Attach Artifact`
Once the PR has been merged into `main`, the same `Action` should be executed again, but then all of the steps will be passed.
**Fixes:** https://github.com/hashgraph/hedera-protobufs-cpp/issues/32
**Checklist**
> Workflow optimisations for PR Checks action (PR)

- CMakeLists.txt
This PR upgrades the `Hedera C++ Protobufs` to use `v0.42.0` of the `Hedera Protobufs API`.
**Fixes**: https://github.com/hashgraph/hedera-protobufs-cpp/issues/34
This PR is just a preparation for upgrading the `Hedera C++ Protobufs` API to the latest available version. 
**Checklist**
> Upgrade to `v0.42.0` of Hedera protobufs (PR)

- CMakeLists.txt
This PR upgrades the `Hedera C++ Protobufs` to use `v0.44.0` of the `Hedera Protobufs API`.
**Fixes**: https://github.com/hashgraph/hedera-protobufs-cpp/issues/38
**Checklist**
> Upgrade to `v0.44.0` of Hedera protobufs (PR)

- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR upgrades the Hedera C++ Protobufs to use `v0.48.1` of the Hedera Protobufs API.
Fixes https://github.com/hashgraph/hedera-protobufs-cpp/issues/44
**Checklist**
> chore: Upgrade Hedera Protobufs to v0.48.1

- .github/workflows/zxc-build-library.yaml
- CMakeLists.txt
- src/proto/CMakeLists.txt
- vcpkg.json
This PR upgrades the Hedera C++ Protobufs to use `v0.49.0-alpha0` of the Hedera Protobufs API.
Fixes https://github.com/hashgraph/hedera-protobufs-cpp/issues/46
**Checklist**
> chore: Upgrade Hedera Protobufs to v0.49.0-alpha0

- .github/workflows/zxc-build-library.yaml
The previous PR for this issue #48 added Android builds when a pull request was merged. However, that was broken and the wrong branch name was being used. This should fix that issue.
Fixes #42 
**Checklist**
> chore: Update branch name for Android builds

- CMakeLists.txt
This PR upgrades the Hedera C++ Protobufs to use v0.50.0 of the Hedera Protobufs API.
Fixes https://github.com/hashgraph/hedera-protobufs-cpp/issues/50
**Checklist**
> chore: Upgrade proto version to v0.50.0

- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR upgrades the Hedera C++ Protobufs to use v0.52.0 of the Hedera Protobufs API.
**Introduced:**
* node_create.proto
* node_delete.proto
* node_update.proto
* token_reject.proto
Fixes https://github.com/hashgraph/hedera-protobufs-cpp/issues/60
**Checklist**
> chore: Upgrade proto version to latest

- .github/workflows/zxc-build-library.yaml
This pull request changes the following:
- Updates the CI workflows `runs-on` labels to use the new Latitude.sh based runners.
- Closes #68
> ci: update workflows to use latitude.sh based runners

- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR upgrades the Hedera C++ Protobufs to use v0.54.0 of the Hedera Protobufs API.
**Introduced:**
* token_airdrop.proto
* token_cancel_airdrop.proto
* token_claim_airdrop.proto
Fixes https://github.com/hashgraph/hedera-protobufs-cpp/issues/72
**Checklist**
> chore: Upgrade Hedera Protobufs version to v0.54.0

- CMakeLists.txt
- src/proto/CMakeLists.txt
This PR upgrades the Hedera C++ Protobufs to use v0.55.0 of the Hedera Protobufs API.
**Introduced:**
* address_book_service.proto
* updates to current protos
Fixes https://github.com/hashgraph/hedera-protobufs-cpp/issues/81
**Checklist**
> chore: Upgrade protobufs version to v0.55.0

- .github/CODEOWNERS
- .github/workflows/zxc-build-library.yaml
Update per Q3 audit findings
Related to #64
**Checklist**
> ci: Update per Q3 audit findings
